### ISSUE TITLE
Add xonsh topics

### ISSUE THREAD

**Issue by anki-code** [eugenesvk/xontrib-linuxbrew#1]
Hi! Great xontrib! Please add `xonsh`, `xontrib`, `brew`, `linuxbrew` topics to the repository About settings.Thanks!

> If you like the idea, ask Homebrew to implement it natively

Done :)

**Comment by eugenesvk** [comment]
Thanks, forgot about that item in the template, added the topics!
Hopefully the Homebrew folks will listen to your stats and revisit their "niche" status!

**Comment by anki-code** [comment]
Don't worry about this. I had many discussions this kind and most maintainers just in a big pressure of job or tasks to understand what is the new thing was proposed. Xonsh is flexible and sometimes to have the xontrib is much better than support integration in the origin repository. You can fix something in minutes or community can give you a PR because the xontrib is simple. It's better than wait for the code review during weeks in origin repo.

Thank you for the xontrib! You rock @eugenesvk !

I suggest #2
