### ISSUE TITLE
Add preview image

### ISSUE THREAD

**Issue by anki-code** [eugenesvk/xontrib-linuxbrew#3]
Hi @eugenesvk !

Please open repository settings and add "Social preview":

![image](https://user-images.githubusercontent.com/1708680/110221321-b5076e00-7edc-11eb-9713-48e883e296bf.png)

Now you can check it here - https://github.com/topics/xontrib

Thanks!

**Comment by anki-code** [comment]
And please star your repo :)

**Comment by eugenesvk** [comment]
Thanks, nice picture!
