### ISSUE TITLE
Xonsh has `source-bash` builtin

### ISSUE THREAD

**Issue by anki-code** [eugenesvk/xontrib-linuxbrew#4]
Hi @eugenesvk !

I've taken a short look at the code and want to introduce [`source-bash` builtin](https://xon.sh/aliases.html#source-bash) to you. To source the bash code you can just run:
```python
source-bash $(/home/$USER/.linuxbrew/bin/brew shellenv)
```
and you can avoid parsing the bash manually.

After this command you can check the values of `$PATH`, `$HOMEBREW_PREFIX`, etc and found it's actual for Brew.

Enjoy :)

**Comment by eugenesvk** [comment]
Thanks for the suggestion, it does look much simpler, but as far as I understand it this reads my whole bash environment into xonsh, which is the reason that:

- it pollutes aliases (even if it doesn't overwrite anything without an extra flag)
- more importantly, it pollutes paths (I get duplicate and empty paths)
- and even more importantly, it's noticeably slower (.9 sec vs .08 sec)

**Comment by anki-code** [comment]
> this reads my whole bash environment 

~Nope, it reads only the output of the `brew shellenv`.~ UPD: understood

> it pollutes aliases

~I see no aliases in the brew output or what you mean?~  UPD: understood

> it pollutes paths (I get duplicate and empty paths)

~Why? If you have no brew paths in your PATH it will be added and nothing else.~ UPD: understood

> it's noticeably slower

This is strange i have much faster timing (WSL):
```python
timeit! source-bash $(/home/$USER/.linuxbrew/bin/brew shellenv)  --suppress-skip-message
# 10 loops, best of 3: 27.2 ms per loop
```

**Comment by anki-code** [comment]
Hm, I understood what you mean. I think this should be a feature to load only new variables.

**Comment by eugenesvk** [comment]
By the way, I used `import time; start_time = time.time(); source-bash $(/home/linuxbrew/.linuxbrew/bin/brew shellenv) --suppress-skip-message; print("--- %s seconds ---" % (time.time() -start_time))` as `timeit` warned me that there is some cache issue (I also got low `ms` there, but then it was visibly slower, and that experience matches the single run riming above)

**Comment by anki-code** [comment]
Yeah, I think you can use `xontrib load linuxbrew` instead of `source-bash` in 4151. The xontrib helps again )
