### ISSUE TITLE
Can't load linuxbrew when xonsh is login shell (on Linux)

### ISSUE THREAD

**Issue by egnor** [eugenesvk/xontrib-linuxbrew#5]
Hi! This module is quite lovely. And it works great when I run `xonsh` from another shell (e.g. zsh).

However, if I set xonsh as my login shell and go ahead and launch a terminal that loads it from scratch, the attempt fails:

```
$ xontrib load linuxbrew
UnboundLocalError: local variable 'path' referenced before assignment
Failed to load xontrib linuxbrew.
```

This was quite mysterious to me so I turned tracing on and got this:

```
$ trace on linuxbrew.xsh
$ source linuxbrew.xsh 
linuxbrew.xsh:1:from xonsh import platform
linuxbrew.xsh:2:from os import path
linuxbrew.xsh:4:__all__ = ()
linuxbrew.xsh:6:_log = __xonsh__.env.get('XONTRIB_LINUXBREW_LOGLEVEL', 1) # 0 none, 1 error, 2 warning, 3 extra
linuxbrew.xsh:8:def _SetBrewEnv():
linuxbrew.xsh:83:_SetBrewEnv()
linuxbrew.xsh:8:def _SetBrewEnv():
linuxbrew.xsh:9:  if not platform.ON_LINUX:
linuxbrew.xsh:13:  if 'HOMEBREW_PREFIX' in ${...}: # don't overwrite existing env var
linuxbrew.xsh:17:  LBS = ''
linuxbrew.xsh:18:  if p'/home/linuxbrew/.linuxbrew/bin/brew'.exists():
linuxbrew.xsh:20:  elif pf'{path.join(path.expanduser("~"), ".linuxbrew/bin/brew")}'.exists():
You may be attempting to source non-xonsh file! If you are trying to source a file in another language, then please use the appropriate source command. For example, source-bash script.sh
UnboundLocalError: local variable 'path' referenced before assignment
$ trace off linuxbrew.xsh
```

This _appears_ to be because, much later in the function, you use `path` as a local variable:

```
for path in reversed(cmdVal):
  ${cmdVar}.add(path, front=True, replace=True) # env lookup 'PATH' and add each path
```

This causes `path` to be considered local, generating an error and ignoring the global import. I actually don't know how this normally works when running as a subshell! But, changing the for-loop to use `p` instead of `path` seems to fix the problem.

**Comment by eugenesvk** [comment]
Hi! Thanks for the investigation, your explanation seems correct and I've added a fix.

Not sure, though, why the login/subshell affects anything, it seems like whenever the non-default Linuxbrew installation code path https://github.com/eugenesvk/xontrib-linuxbrew/blob/1b26eac132ebc8be1a5889bf13808e9171b49a4b/xontrib/linuxbrew.xsh#L20 is triggered that uses the imported `path` module you should get an `UnboundLocalError` even in a subshell (I've added a `path.join` command for the default installation path and I get this error in both subshell/login shell cases)... 
Unless there is something else that prevents the local var path loop from starting (like this break https://github.com/eugenesvk/xontrib-linuxbrew/blob/1b26eac132ebc8be1a5889bf13808e9171b49a4b/xontrib/linuxbrew.xsh#L64, which might indicate some other issue with parsing Linuxbrew's env export commands?

Would you kindly check that with your install (with the old xontrib version to trigger the `UnboundLocalError`) — e.g. add a `print('test')` command or something before [this break](https://github.com/eugenesvk/xontrib-linuxbrew/blob/main/xontrib/linuxbrew.xsh#L65)?
Or maybe just add `print(LBS)` before this line https://github.com/eugenesvk/xontrib-linuxbrew/blob/1b26eac132ebc8be1a5889bf13808e9171b49a4b/xontrib/linuxbrew.xsh#L26
to see if your output matches the one that this xontrib is parsing?

**Comment by egnor** [comment]
The reason it was working when started from the old shell is quite straightforward when I look into it! My old shell's startup files sourced `brew shellenv`, thus placing `$HOMEBREW_PREFIX` in the environment (and doing all its other environment updates), so `linuxbrew.xsh` (quite correctly) noticed this and exited early.
